In [1]:
import numpy as np
from primitive import arange, where, tensor

## [ones](https://numpy.org/doc/stable/reference/generated/numpy.ones.html)

In [2]:
# example
np.ones(5)

array([1., 1., 1., 1., 1.])

In [3]:
def ones(n: int):
    pass

In [4]:
# ones(5)

In [5]:
# # test
# assert (ones(5) == np.ones(5)).all(), f"Mismatch: {ones(5)} != {np.ones(5)}"
# assert (ones(0) == np.ones(0)).all(), f"Mismatch: {ones(0)} != {np.ones(0)}"

## [sum](https://numpy.org/doc/stable/reference/generated/numpy.sum.html)

In [6]:
# example
np.arange(5), np.sum(np.arange(5))

(array([0, 1, 2, 3, 4]), 10)

In [7]:
def sum(a_i):
    pass

In [8]:
# sum(arange(5))

In [9]:
# # test
# assert sum(np.array([1, 2, 3, 4])) == 10, f"Sum mismatch: {sum(np.array([1, 2, 3, 4]))} != 10"
# assert sum(np.array([])) == 0, f"Sum mismatch: {sum(np.array([]))} != 0"
# assert sum(np.array([-1, 1])) == 0, f"Sum mismatch: {sum(np.array([-1, 1]))} != 0"

## [outer](https://numpy.org/doc/stable/reference/generated/numpy.outer.html)

In [10]:
# example
np.outer(np.arange(3), np.ones(5))

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.]])

In [11]:
def outer(a_i, b_j):
    pass

In [12]:
# outer(arange(3), ones(5))

In [13]:
# # test
# assert np.array_equal(outer(np.array([1, 2]), np.array([1, 2])), np.outer(np.array([1, 2]), np.array([1, 2]))), "Outer product mismatch"
# assert np.array_equal(outer(np.array([0, 1]), np.array([0, 1])), np.outer(np.array([0, 1]), np.array([0, 1]))), "Outer product mismatch"
# assert np.array_equal(outer(np.array([-1, 1]), np.array([-1, 1])), np.outer(np.array([-1, 1]), np.array([-1, 1]))), "Outer product mismatch"

## [diag](https://numpy.org/doc/stable/reference/generated/numpy.diag.html)

In [14]:
# example
a_33 = np.arange(9).reshape((3, 3))
a_33, np.diag(a_33)

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([0, 4, 8]))

In [15]:
def diag(a_ii):  # input has to be square matrix
    pass

In [16]:
# diag(a_33)

In [17]:
# # test
# assert np.array_equal(diag(np.array([[1, 2], [3, 4]])), np.diag(np.array([[1, 2], [3, 4]]))), "Diagonal extraction mismatch"
# assert np.array_equal(diag(np.array([[0, 1], [1, 0]])), np.diag(np.array([[0, 1], [1, 0]]))), "Diagonal extraction mismatch"
# assert np.array_equal(diag(np.array([[-1, -2], [-3, -4]])), np.diag(np.array([[-1, -2], [-3, -4]]))), "Diagonal extraction mismatch"

## [eye](https://numpy.org/doc/stable/reference/generated/numpy.eye.html)

In [18]:
# example
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
def eye(n: int):
    pass

In [20]:
# eye(3)

In [21]:
# # test
# assert np.array_equal(eye(3), np.eye(3)), "Identity matrix generation mismatch"
# assert np.array_equal(eye(5), np.eye(5)), "Identity matrix generation mismatch"
# assert np.array_equal(eye(1), np.eye(1)), "Identity matrix generation mismatch"

## [triu](https://numpy.org/doc/stable/reference/generated/numpy.triu.html)

In [22]:
# example
a_33 = np.arange(9).reshape((3, 3))
a_33, np.triu(a_33)

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[0, 1, 2],
        [0, 4, 5],
        [0, 0, 8]]))

In [23]:
def triu(a_ii):
    pass

In [24]:
# triu(a_33)

In [25]:
# # test
# assert np.array_equal(triu(np.arange(9).reshape((3, 3))), np.triu(np.arange(9).reshape((3, 3)))), "Upper triangle matrix generation mismatch"
# assert np.array_equal(triu(np.arange(4).reshape((2, 2))), np.triu(np.arange(4).reshape((2, 2)))), "Upper triangle matrix generation mismatch"
# assert np.array_equal(triu(np.zeros((3, 3))), np.triu(np.zeros((3, 3)))), "Upper triangle matrix generation mismatch"

## [cumsum](https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html)

In [26]:
# example
np.cumsum(np.ones(10))

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [27]:
def cumsum(a_i):
    pass

In [28]:
# cumsum(ones(10))

In [29]:
# # test
# assert np.array_equal(cumsum(np.arange(10)), np.cumsum(np.arange(10))), "Cumulative sum mismatch"
# assert np.array_equal(cumsum(np.zeros(10)), np.cumsum(np.zeros(10))), "Cumulative sum mismatch for zeros"
# assert np.array_equal(cumsum(np.ones(10)), np.cumsum(np.ones(10))), "Cumulative sum mismatch for ones"

## [diff](https://numpy.org/doc/stable/reference/generated/numpy.diff.htm)

In [30]:
# example
np.diff(np.arange(5))

array([1, 1, 1, 1])

In [31]:
def diff(a_i):
    pass

In [32]:
# diff(arange(5))

In [33]:
# # test
# random_array = np.random.randint(0, 10, size=5)
# assert np.array_equal(diff(random_array), np.diff(random_array)), "Difference mismatch for random array"
# assert np.array_equal(diff(np.zeros(5)), np.diff(np.zeros(5))), "Difference mismatch for zeros"
# assert np.array_equal(diff(np.ones(5)), np.diff(np.ones(5))), "Difference mismatch for ones"


## [vstack](https://numpy.org/doc/stable/reference/generated/numpy.vstack.html)

In [34]:
# example
np.vstack((np.ones(5), np.arange(5)))

array([[1., 1., 1., 1., 1.],
       [0., 1., 2., 3., 4.]])

In [35]:
def vstack(a_i, b_i):
    pass

In [36]:
# vstack(ones(5), arange(5))

In [37]:
# # test
# length1 = np.random.randint(1, 10)
# assert np.array_equal(vstack(ones(length1), arange(length1)), np.vstack((ones(length1), arange(length1)))), "vstack mismatch for ones and arange with random length"

# length2 = np.random.randint(1, 10)
# assert np.array_equal(vstack(arange(length2), arange(length2)), np.vstack((arange(length2), arange(length2)))), "vstack mismatch for two aranges with same random length"

# length3 = np.random.randint(1, 10)
# assert np.array_equal(vstack(arange(length3), ones(length3)), np.vstack((arange(length3), ones(length3)))), "vstack mismatch for arange and ones with random length"


## [roll](https://numpy.org/doc/stable/reference/generated/numpy.roll.html)

In [38]:
# example
np.roll(np.arange(5), shift=-1)  # negative, shift left

array([1, 2, 3, 4, 0])

In [39]:
def roll(a_i):
    pass

In [40]:
# roll(arange(5))

In [41]:
# # test
# # fmt: off
# test_arrays = [
#     (np.random.randint(1, 10), arange, "arange with random length"),
#     (np.random.randint(1, 10), lambda x: np.random.randint(0, 100, size=x), "random array with random length"),
#     (10, lambda x: np.linspace(0, 1, x), "linspace array with fixed length")
# ]

# for length, array_func, description in test_arrays:
#     test_array = array_func(length)
#     assert np.array_equal(roll(test_array), np.roll(test_array, shift=-1)), f"roll mismatch for {description}: {length}, roll: {roll(test_array)}, np.roll: {np.roll(test_array, shift=1)}"
# # fmt: on

## [flip](https://numpy.org/doc/stable/reference/generated/numpy.flip.html)

In [42]:
# example
np.flip(np.arange(5))

array([4, 3, 2, 1, 0])

In [43]:
def flip(a_i):
    pass

In [44]:
# flip(arange(5))

In [45]:
# # test
# # fmt: off
# test_arrays_flip = [
#     (arange(5), "arange with fixed length"),
#     (np.random.randint(0, 100, size=10), "random array with fixed length"),
#     (np.array([0, -1, -2, -3, 0, 1, 2, 3, 0]), "array with negative numbers and zeros")
# ]

# for test_array, description in test_arrays_flip:
#     assert np.array_equal(flip(test_array), np.flip(test_array)), f"flip mismatch for {description}: {test_array}, flip: {flip(test_array)}, np.flip: {np.flip(test_array)}"
# # fmt: on

## [compress](https://numpy.org/doc/stable/reference/generated/numpy.compress.html)

In [46]:
# example
np.compress(condition=tensor([True, False, True, False]), a=np.arange(4))

array([0, 2])

In [47]:
def compress(condition_i, a_i):
    pass

In [48]:
# compress(tensor([True, False, True, False]), arange(4))

In [49]:
# # test
# # Test 1: Alternating condition
# condition_1 = tensor([True, False, True, False])
# test_array_1 = arange(4)
# assert np.array_equal(compress(condition_1, test_array_1), np.compress(condition_1, test_array_1)), "Test 1 failed: compress mismatch with np.compress for alternating condition"

# # Test 2: All true except last
# condition_2 = tensor([True, True, True, False])
# test_array_2 = arange(4)
# assert np.array_equal(compress(condition_2, test_array_2), np.compress(condition_2, test_array_2)), "Test 2 failed: compress mismatch with np.compress for all true except last"

# # Test 3: All false except last two
# condition_3 = tensor([False, False, True, True])
# test_array_3 = arange(4)
# assert np.array_equal(compress(condition_3, test_array_3), np.compress(condition_3, test_array_3)), "Test 3 failed: compress mismatch with np.compress for all false except last two"

## pad to
- Pad `[0, 1, 2]` to len 8 -> `[0, 1, 2, 0, 0, 0, 0, 0]`

In [50]:
def pad_to(a_i, j: int):
    """pad to len j, where j >= i"""
    pass


In [51]:
# pad_to(arange(3), 8)

In [52]:
# # test
# padded_array = pad_to(arange(3), 8)
# assert padded_array.shape[0] == 8, f"Length mismatch for pad to len 8: expected 8, got {padded_array.shape[0]}"
# assert np.array_equal(padded_array[:3], arange(3)), "Original elements altered in pad to len 8"
# assert np.all(padded_array[3:] == 0), "Padding not zeros in pad to len 8"

# padded_array = pad_to(arange(5), 10)
# assert padded_array.shape[0] == 10, f"Length mismatch for pad to len 10: expected 10, got {padded_array.shape[0]}"
# assert np.array_equal(padded_array[:5], arange(5)), "Original elements altered in pad to len 10"
# assert np.all(padded_array[5:] == 0), "Padding not zeros in pad to len 10"

# padded_array = pad_to(np.zeros(4), 6)
# assert padded_array.shape[0] == 6, f"Length mismatch for pad zeros to len 6: expected 6, got {padded_array.shape[0]}"
# assert np.array_equal(padded_array[:4], np.zeros(4)), "Original elements altered in pad zeros to len 6"
# assert np.all(padded_array[4:] == 0), "Padding not zeros in pad zeros to len 6"


## [sequence mask](https://www.tensorflow.org/api_docs/python/tf/sequence_mask)

```python
tf.sequence_mask(
    lengths,
    maxlen=None,
)

tf.sequence_mask([1, 3, 2], 5)  # [[True, False, False, False, False],
                                #  [True, True, True, False, False],
                                #  [True, True, False, False, False]]

In [53]:
def seq_mask(len_B: list[int], maxlen: int):
    """assume maxlen >= len of longest seq in the len_B
    B: batch size
    maxlen: pad the batch to this len
    """
    pass

In [54]:
# seq_mask(tensor([1, 3, 2]), 5)

In [55]:
# # test
# result_1 = seq_mask(tensor([1, 3, 2]), 5)
# expected_1 = np.array([[True, False, False, False, False],
#                         [True, True, True, False, False],
#                         [True, True, False, False, False]])
# assert np.array_equal(result_1, expected_1), f"Test 1 failed: expected {expected_1}, got {result_1}"

# result_2 = seq_mask(tensor([0, 4, 1]), 4)
# expected_2 = np.array([[False, False, False, False],
#                         [True, True, True, True],
#                         [True, False, False, False]])
# assert np.array_equal(result_2, expected_2), f"Test 2 failed: expected {expected_2}, got {result_2}"

# result_3 = seq_mask(tensor([5]), 5)
# expected_3 = np.array([[True, True, True, True, True]])
# assert np.array_equal(result_3, expected_3), f"Test 3 failed: expected {expected_3}, got {result_3}"

## [bincount](https://numpy.org/doc/stable/reference/generated/numpy.bincount.html)

In [56]:
# example
np.bincount(np.array([0, 1, 1, 3, 2, 1, 7]))

array([1, 3, 1, 1, 0, 0, 0, 1])

In [57]:
def bincount(a_i):
    pass

In [58]:
# bincount(tensor([0, 1, 1, 3, 2, 1, 7]))

In [59]:
# # test
# my_result_1 = bincount(tensor([0, 1, 1, 3, 2, 1, 7]))
# np_result_1 = np.bincount(np.array([0, 1, 1, 3, 2, 1, 7]))
# assert np.array_equal(my_result_1, np_result_1), f"Test 1 failed: expected {np_result_1}, got {my_result_1}"

# my_result_2 = bincount(tensor([2, 3, 3, 2, 4]))
# np_result_2 = np.bincount(np.array([2, 3, 3, 2, 4]))
# assert np.array_equal(my_result_2, np_result_2), f"Test 2 failed: expected {np_result_2}, got {my_result_2}"

# my_result_3 = bincount(tensor([0, 0, 0]))
# np_result_3 = np.bincount(np.array([0, 0, 0]))
# assert np.array_equal(my_result_3, np_result_3), f"Test 3 failed: expected {np_result_3}, got {my_result_3}"


## [scatter add](https://pytorch-scatter.readthedocs.io/en/1.3.0/functions/add.html)
![](https://raw.githubusercontent.com/rusty1s/pytorch_scatter/master/docs/source/_figures/add.svg?sanitize=true)

In [60]:
def scatter_add(a_i, index_i):
    pass  

In [61]:
# a = tensor([5, 1, 7, 2, 3, 2, 1, 3])
# index = tensor([0, 0, 1, 0, 2, 2, 3, 3])

# scatter_add(a, index)

In [62]:
# # test
# result_1 = scatter_add(tensor([5, 1, 7, 2, 3, 2, 1, 3]), tensor([0, 0, 1, 0, 2, 2, 3, 3]))
# expected_1 = np.array([8, 7, 5, 4])
# assert np.array_equal(result_1, expected_1), f"Test 1 failed: expected {expected_1}, got {result_1}"

# result_2 = scatter_add(tensor([2, 4, 1, 3]), tensor([1, 1, 0, 1]))
# expected_2 = np.array([1, 9])
# assert np.array_equal(result_2, expected_2), f"Test 2 failed: expected {expected_2}, got {result_2}"

# result_3 = scatter_add(tensor([0, 0, 0, 0]), tensor([0, 1, 2, 3]))
# expected_3 = np.array([0, 0, 0, 0])
# assert np.array_equal(result_3, expected_3), f"Test 3 failed: expected {expected_3}, got {result_3}"

## [flattern](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flatten.html)

In [63]:
# example
a = np.arange(12).reshape((3, 4))
a, a.flatten()

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]))

In [64]:
def flatten(a_ij):
    pass

In [65]:
# flatten(a)

In [66]:
# # test
# a_test_1 = np.array([[1, 2], [3, 4]])
# expected_1 = a_test_1.flatten()
# result_1 = flatten(a_test_1)
# assert np.array_equal(result_1, expected_1), f"Test 1 failed: expected {expected_1}, got {result_1}"

# a_test_2 = np.array([[0, 0, 0], [0, 0, 0]])
# expected_2 = a_test_2.flatten()
# result_2 = flatten(a_test_2)
# assert np.array_equal(result_2, expected_2), f"Test 2 failed: expected {expected_2}, got {result_2}"

# a_test_3 = np.array([[9]])
# expected_3 = a_test_3.flatten()
# result_3 = flatten(a_test_3)
# assert np.array_equal(result_3, expected_3), f"Test 3 failed: expected {expected_3}, got {result_3}"

## [linspace](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html)

In [67]:
# example
np.linspace(2, 3, 5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [68]:
def linspace(start, stop, n: int):
    """inclusive for both start and stop"""
    pass

In [69]:
# linspace(2, 3, 5)

In [70]:
# # test
# test_1_start, test_1_stop, test_1_n = -10, 0, 5
# expected_1 = np.linspace(test_1_start, test_1_stop, test_1_n)
# result_1 = linspace(test_1_start, test_1_stop, test_1_n)
# assert np.allclose(result_1, expected_1), f"Test 1 failed: expected {expected_1}, got {result_1}"

# test_2_start, test_2_stop, test_2_n = 0, 100, 20
# expected_2 = np.linspace(test_2_start, test_2_stop, test_2_n)
# result_2 = linspace(test_2_start, test_2_stop, test_2_n)
# assert np.allclose(result_2, expected_2), f"Test 2 failed: expected {expected_2}, got {result_2}"

# test_3_start, test_3_stop, test_3_n = -50, 50, 2
# expected_3 = np.linspace(test_3_start, test_3_stop, test_3_n)
# result_3 = linspace(test_3_start, test_3_stop, test_3_n)
# assert np.allclose(result_3, expected_3), f"Test 3 failed: expected {expected_3}, got {result_3}"

## [heaviside](https://numpy.org/doc/stable/reference/generated/numpy.heaviside.html)
```python
                      0   if x1 < 0
heaviside(x1, x2) =  x2   if x1 == 0
                      1   if x1 > 0
```

In [71]:
np.heaviside([-1.5, 0, 2.0], 1)

array([0., 1., 1.])

In [72]:
def heaviside(a_i, b):
    pass

In [73]:
# heaviside(tensor([-1.5, 0, 2.0]), 1)

In [74]:
# # test
# test_1_input = np.array([-2.5, 0, 3.5])
# expected_1 = np.heaviside(test_1_input, 0.5)
# result_1 = heaviside(test_1_input, 0.5)
# assert np.allclose(result_1, expected_1), f"Test 1 failed: expected {expected_1}, got {result_1}"

# test_2_input = np.array([-100, -50, 0, 50, 100])
# expected_2 = np.heaviside(test_2_input, 0.8)
# result_2 = heaviside(test_2_input, 0.8)
# assert np.allclose(result_2, expected_2), f"Test 2 failed: expected {expected_2}, got {result_2}"

# test_3_input = np.array([0])
# expected_3 = np.heaviside(test_3_input, 0)
# result_3 = heaviside(test_3_input, 0)
# assert np.allclose(result_3, expected_3), f"Test 3 failed: expected {expected_3}, got {result_3}"

## [repeat(1d)](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

The effect of `np.tile`, but only expand on `dim=0`. 


In [75]:
# example
np.tile(np.arange(3), (5, 1))

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [76]:
def repeat(a_i, n: int):
    pass

In [77]:
# repeat(arange(3), 5)

In [78]:
# # test
# test_1_input = arange(4)
# n_1 = 3
# expected_1 = np.tile(test_1_input, (n_1, 1))
# result_1 = repeat(test_1_input, n_1)
# assert np.array_equal(result_1, expected_1), f"Test 1 failed: expected {expected_1}, got {result_1}"

# test_2_input = tensor([5])
# n_2 = 10
# expected_2 = np.tile(test_2_input, (n_2, 1))
# result_2 = repeat(test_2_input, n_2)
# assert np.array_equal(result_2, expected_2), f"Test 2 failed: expected {expected_2}, got {result_2}"

# test_3_input = linspace(0, 1, 5)
# n_3 = 2
# expected_3 = np.tile(test_3_input, (n_3, 1))
# result_3 = repeat(test_3_input, n_3)
# assert np.array_equal(result_3, expected_3), f"Test 3 failed: expected {expected_3}, got {result_3}"


# [bucketize](https://pytorch.org/docs/stable/generated/torch.bucketize.html)

Returns the **indices** of the buckets to which each value in the input belongs.

```python
a = torch.tensor([3, 6, 9])
boundary = torch.tensor([1, 3, 5, 7, 9])

torch.bucketize(a, boundary) -> tensor([1, 3, 4])
```

In [79]:
def bucketize(a_i, boundary_j):
    """boundary has to be in monotonically increasing order."""
    pass

In [80]:
# a = tensor([3, 6, 9])
# boundary = tensor([1, 3, 5, 7, 9])

# bucketize(a, boundary)

In [81]:
# # test
# test_1_input = tensor([0, 5, 10])
# boundary_1 = tensor([0, 3, 6, 9])
# expected_1 = tensor([0, 2, 4])
# result_1 = bucketize(test_1_input, boundary_1)
# assert np.array_equal(result_1, expected_1), f"Test 1 failed: expected {expected_1}, got {result_1}"

# test_2_input = tensor([-5, 0, 5, 10])
# boundary_2 = tensor([-10, -5, 0, 5, 10])
# expected_2 = tensor([1, 2, 3, 4])
# result_2 = bucketize(test_2_input, boundary_2)
# assert np.array_equal(result_2, expected_2), f"Test 2 failed: expected {expected_2}, got {result_2}"

# test_3_input = tensor([1, 2, 3, 4, 5])
# boundary_3 = tensor([1, 3, 5])
# expected_3 = tensor([0, 1, 1, 2, 2])
# result_3 = bucketize(test_3_input, boundary_3)
# assert np.array_equal(result_3, expected_3), f"Test 3 failed: expected {expected_3}, got {result_3}"
