In [1]:
import numpy as np
from primitive import arange, where, tensor

## [ones](https://numpy.org/doc/stable/reference/generated/numpy.ones.html)
- To think in tensor way, replace traditional iterative programming primitives with basic tensor ops. 
- `arange` and `broadcast` to replace `for loop`. 
- `where` to replace `if-else`. 

In [2]:
# example
np.ones(5)

array([1., 1., 1., 1., 1.])

In [3]:
# v1
# def ones(n: int):
#     return arange(n) * 0 + 1

# v2
def ones(n: int):
    return where(arange(n) == 1, 1, 1)

In [4]:
ones(5)

array([1, 1, 1, 1, 1])

In [5]:
# test
assert (ones(5) == np.ones(5)).all(), f"Mismatch: {ones(5)} != {np.ones(5)}"
assert (ones(0) == np.ones(0)).all(), f"Mismatch: {ones(0)} != {np.ones(0)}"

## [sum](https://numpy.org/doc/stable/reference/generated/numpy.sum.html)
- Think about `@`, which could be `matmul` or `dot product`, to reduce dimension. 

In [6]:
# example
arange(5), np.sum(arange(5))

(array([0, 1, 2, 3, 4]), 10)

In [7]:
# v1
def sum(a_i):
    i = a_i.shape[0]
    return a_i @ ones(i)

In [8]:
sum(arange(5))

10

In [9]:
# test
assert sum(np.array([1, 2, 3, 4])) == 10, f"Sum mismatch: {sum(np.array([1, 2, 3, 4]))} != 10"
assert sum(np.array([])) == 0, f"Sum mismatch: {sum(np.array([]))} != 0"
assert sum(np.array([-1, 1])) == 0, f"Sum mismatch: {sum(np.array([-1, 1]))} != 0"

## [outer](https://numpy.org/doc/stable/reference/generated/numpy.outer.html)
- `a[:, None]` adds a `dim=1` at the end. 
- Think about adding dummy dimension and use broadcast rule to expand the dimension. 

In [10]:
# example
np.outer(arange(3), ones(5))

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2]])

In [11]:
def outer(a_i, b_j):
    return a_i[:, None] * b_j

In [12]:
outer(arange(3), ones(5))

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2]])

In [13]:
# test
assert np.array_equal(outer(np.array([1, 2]), np.array([1, 2])), np.outer(np.array([1, 2]), np.array([1, 2]))), "Outer product mismatch"
assert np.array_equal(outer(np.array([0, 1]), np.array([0, 1])), np.outer(np.array([0, 1]), np.array([0, 1]))), "Outer product mismatch"
assert np.array_equal(outer(np.array([-1, 1]), np.array([-1, 1])), np.outer(np.array([-1, 1]), np.array([-1, 1]))), "Outer product mismatch"

## [diag](https://numpy.org/doc/stable/reference/generated/numpy.diag.html)
- Think about indexing for retrival puzzle. 

In [14]:
# example
a_33 = arange(9).reshape((3, 3))
a_33, np.diag(a_33)

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([0, 4, 8]))

In [15]:
def diag(a_ii):  # input has to be square matrix
    i = a_ii.shape[0]
    return a_ii[arange(i), arange(i)]

In [16]:
diag(a_33)

array([0, 4, 8])

In [17]:
# test
assert np.array_equal(diag(np.array([[1, 2], [3, 4]])), np.diag(np.array([[1, 2], [3, 4]]))), "Diagonal extraction mismatch"
assert np.array_equal(diag(np.array([[0, 1], [1, 0]])), np.diag(np.array([[0, 1], [1, 0]]))), "Diagonal extraction mismatch"
assert np.array_equal(diag(np.array([[-1, -2], [-3, -4]])), np.diag(np.array([[-1, -2], [-3, -4]]))), "Diagonal extraction mismatch"

## [eye](https://numpy.org/doc/stable/reference/generated/numpy.eye.html)
- Semantically, it's similar to `outer` above. Add a dim plus simple op to expand to 2d, then use `where` to cast `bool` to `int` for final result. 

In [18]:
# example
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
def eye(n: int):
    return where(arange(n)[:, None] == arange(n), 1, 0)

In [20]:
eye(3)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [21]:
# test
assert np.array_equal(eye(3), np.eye(3)), "Identity matrix generation mismatch"
assert np.array_equal(eye(5), np.eye(5)), "Identity matrix generation mismatch"
assert np.array_equal(eye(1), np.eye(1)), "Identity matrix generation mismatch"

## [triu](https://numpy.org/doc/stable/reference/generated/numpy.triu.html)
- It is the key to `attention` mechanism. 
- Semantically, use same trick of `eye`. 

In [22]:
# example
a_33 = arange(9).reshape((3, 3))
a_33, np.triu(a_33)

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[0, 1, 2],
        [0, 4, 5],
        [0, 0, 8]]))

In [23]:
def triu(a_ii):
    i = a_ii.shape[0]
    cond = arange(i)[:, None] <= arange(i)
    return where(cond, a_ii, 0)

In [24]:
triu(a_33)

array([[0, 1, 2],
       [0, 4, 5],
       [0, 0, 8]])

In [25]:
# test
assert np.array_equal(triu(np.arange(9).reshape((3, 3))), np.triu(np.arange(9).reshape((3, 3)))), "Upper triangle matrix generation mismatch"
assert np.array_equal(triu(np.arange(4).reshape((2, 2))), np.triu(np.arange(4).reshape((2, 2)))), "Upper triangle matrix generation mismatch"
assert np.array_equal(triu(np.zeros((3, 3))), np.triu(np.zeros((3, 3)))), "Upper triangle matrix generation mismatch"

## [cumsum](https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html)
- Again, key to attention and why autoregressive transformer training is so efficient and parallelizable. 
- V1 is direct. V2 is what really happen in the transformer attention module. 

Naive pseudo code of attention: 
```python
def attention(q_btc, k_btc, v_btc):
    attn = softmax(q @ rearrange(k, 'b t c -> b c t'))  # (b, t, c) @ (b, c, t) -> (b, t, t)
    attn_mask = where(tril, attn, float('-inf'))
    attn += attn_mask
    return attn @ v  # (b, t, t) @ (b, t, c) -> (b, t, c)
```
`tril` here because each token in `t` dim has `c` channels. It's applying autoregressive `cumsum` per channel. 

In [26]:
# example
np.cumsum(ones(10))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
# v1, vector @ matrix
# def cumsum(a_i):
#     i = a_i.shape[0]
#     return a_i @ triu(ones(i)[:, None] * ones(i))

# v2, matrix @ vector
def cumsum(a_i):
    i = a_i.shape[0]
    tril = where(arange(i)[:, None] >= arange(i), 1, 0)
    return tril @ a_i

In [28]:
cumsum(ones(10))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
# test
assert np.array_equal(cumsum(np.arange(10)), np.cumsum(np.arange(10))), "Cumulative sum mismatch"
assert np.array_equal(cumsum(np.zeros(10)), np.cumsum(np.zeros(10))), "Cumulative sum mismatch for zeros"
assert np.array_equal(cumsum(np.ones(10)), np.cumsum(np.ones(10))), "Cumulative sum mismatch for ones"

## [diff](https://numpy.org/doc/stable/reference/generated/numpy.diff.htm)
- This off by one index is how to construct label for autorepressive training. 

In [30]:
# example
np.diff(arange(5))

array([1, 1, 1, 1])

In [31]:
def diff(a_i):
    i = a_i.shape[0]
    return a_i[arange(i)[1:]] - a_i[arange(i)[:-1]]

In [32]:
diff(arange(5))

array([1, 1, 1, 1])

In [33]:
# test
random_array = np.random.randint(0, 10, size=5)
assert np.array_equal(diff(random_array), np.diff(random_array)), "Difference mismatch for random array"
assert np.array_equal(diff(np.zeros(5)), np.diff(np.zeros(5))), "Difference mismatch for zeros"
assert np.array_equal(diff(np.ones(5)), np.diff(np.ones(5))), "Difference mismatch for ones"


## [vstack](https://numpy.org/doc/stable/reference/generated/numpy.vstack.html)
- Don't have to fully develop the condition, think about broadcast. 

In [86]:
# example
np.vstack((ones(5), arange(5)))

array([[1, 1, 1, 1, 1],
       [0, 1, 2, 3, 4]])

In [87]:
def vstack(a_i, b_i):
    return where((arange(2) == 0)[:, None], a_i, b_i)

In [88]:
vstack(ones(5), arange(5))

array([[1, 1, 1, 1, 1],
       [0, 1, 2, 3, 4]])

In [89]:
# test
length1 = np.random.randint(1, 10)
assert np.array_equal(vstack(ones(length1), arange(length1)), np.vstack((ones(length1), arange(length1)))), "vstack mismatch for ones and arange with random length"

length2 = np.random.randint(1, 10)
assert np.array_equal(vstack(arange(length2), arange(length2)), np.vstack((arange(length2), arange(length2)))), "vstack mismatch for two aranges with same random length"

length3 = np.random.randint(1, 10)
assert np.array_equal(vstack(arange(length3), ones(length3)), np.vstack((arange(length3), ones(length3)))), "vstack mismatch for arange and ones with random length"


## [roll](https://numpy.org/doc/stable/reference/generated/numpy.roll.html)
- My first implementation used direct `where` to deal with index i-1, which works but it's iterative programming thinking. Get used to think in tensors. 
- Whenever you want to deal with special case, the tranditonal if-else kicks in, think again in tensor form.
- Remember the goal of these exercises is not to implement functions, but to twist the brain enough to learn the pattern of tensor ops. 

In [38]:
# example
np.roll(arange(5), shift=-1)  # negative, shift left

array([1, 2, 3, 4, 0])

In [39]:
# v1
# def roll(a_i):
#     i = a_i.shape[0]
#     return a_i[where(arange(i) == i - 1, 0, arange(i) + 1)]


# v2
def roll(a_i):
    i = a_i.shape[0]
    return a_i[(arange(i) + 1) % i]

In [40]:
roll(arange(5))

array([1, 2, 3, 4, 0])

In [41]:
# test
# fmt: off
test_arrays = [
    (np.random.randint(1, 10), arange, "arange with random length"),
    (np.random.randint(1, 10), lambda x: np.random.randint(0, 100, size=x), "random array with random length"),
    (10, lambda x: np.linspace(0, 1, x), "linspace array with fixed length")
]

for length, array_func, description in test_arrays:
    test_array = array_func(length)
    assert np.array_equal(roll(test_array), np.roll(test_array, shift=-1)), f"roll mismatch for {description}: {length}, roll: {roll(test_array)}, np.roll: {np.roll(test_array, shift=1)}"
# fmt: on

## [flip](https://numpy.org/doc/stable/reference/generated/numpy.flip.html)
- For each position, original index and the flipped index sums to `i - 1`. 

In [42]:
# example
np.flip(arange(5))

array([4, 3, 2, 1, 0])

In [43]:
def flip(a_i):
    i = a_i.shape[0]
    return a_i[i - 1 - arange(i)]

In [44]:
flip(arange(5))

array([4, 3, 2, 1, 0])

In [45]:
# test
# fmt: off
test_arrays_flip = [
    (arange(5), "arange with fixed length"),
    (np.random.randint(0, 100, size=10), "random array with fixed length"),
    (np.array([0, -1, -2, -3, 0, 1, 2, 3, 0]), "array with negative numbers and zeros")
]

for test_array, description in test_arrays_flip:
    assert np.array_equal(flip(test_array), np.flip(test_array)), f"flip mismatch for {description}: {test_array}, flip: {flip(test_array)}, np.flip: {np.flip(test_array)}"
# fmt: on

## [compress](https://numpy.org/doc/stable/reference/generated/numpy.compress.html)

In [46]:
# example
np.compress(condition=tensor([True, False, True, False]), a=arange(4))

array([0, 2])

In [47]:
def compress(condition_i, a_i):
    return a_i[condition_i]

In [48]:
compress(tensor([True, False, True, False]), arange(4))

array([0, 2])

In [49]:
# test
# Test 1: Alternating condition
condition_1 = tensor([True, False, True, False])
test_array_1 = arange(4)
assert np.array_equal(compress(condition_1, test_array_1), np.compress(condition_1, test_array_1)), "Test 1 failed: compress mismatch with np.compress for alternating condition"

# Test 2: All true except last
condition_2 = tensor([True, True, True, False])
test_array_2 = arange(4)
assert np.array_equal(compress(condition_2, test_array_2), np.compress(condition_2, test_array_2)), "Test 2 failed: compress mismatch with np.compress for all true except last"

# Test 3: All false except last two
condition_3 = tensor([False, False, True, True])
test_array_3 = arange(4)
assert np.array_equal(compress(condition_3, test_array_3), np.compress(condition_3, test_array_3)), "Test 3 failed: compress mismatch with np.compress for all false except last two"

## pad to
- pad `[0, 1, 2]` to len 8 -> `[0, 1, 2, 0, 0, 0, 0, 0]`
- Think about dimension change as [linear transformations](https://www.youtube.com/watch?v=kYB8IZa5AuE&list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab&index=3).
- Padding is applying a matrix to the source vector. 
- Padding is adding dimensions, new dim's basis vectors are all 0s. 
- Projection from low dim to high dim in this way won't introduce info loss or distortion. 

In [50]:
def pad_to(a_i, j: int):
    """pad to len j, where j >= i"""
    i = a_i.shape[0]
    basis_vector_mapping = where(arange(i)[:, None] == arange(j), 1, 0)
    return a_i @ basis_vector_mapping

In [51]:
pad_to(arange(3), 8)

array([0, 1, 2, 0, 0, 0, 0, 0])

In [52]:
# see that xyz basis vector, from the source, didn't change at all. 
# basis vectors of padded dims are all zero, since there is no info mapping from source dim to padded dim. 
# padded dimension is dummy dimension, which has no entropy. 
where(arange(3)[:, None] == arange(8), 1, 0)

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0]])

In [53]:
# test
padded_array = pad_to(arange(3), 8)
assert padded_array.shape[0] == 8, f"Length mismatch for pad to len 8: expected 8, got {padded_array.shape[0]}"
assert np.array_equal(padded_array[:3], arange(3)), "Original elements altered in pad to len 8"
assert np.all(padded_array[3:] == 0), "Padding not zeros in pad to len 8"

padded_array = pad_to(arange(5), 10)
assert padded_array.shape[0] == 10, f"Length mismatch for pad to len 10: expected 10, got {padded_array.shape[0]}"
assert np.array_equal(padded_array[:5], arange(5)), "Original elements altered in pad to len 10"
assert np.all(padded_array[5:] == 0), "Padding not zeros in pad to len 10"

padded_array = pad_to(np.zeros(4), 6)
assert padded_array.shape[0] == 6, f"Length mismatch for pad zeros to len 6: expected 6, got {padded_array.shape[0]}"
assert np.array_equal(padded_array[:4], np.zeros(4)), "Original elements altered in pad zeros to len 6"
assert np.all(padded_array[4:] == 0), "Padding not zeros in pad zeros to len 6"


## [sequence mask](https://www.tensorflow.org/api_docs/python/tf/sequence_mask)

```python
tf.sequence_mask(
    lengths,
    maxlen=None,
)

tf.sequence_mask([1, 3, 2], 5)  # [[True, False, False, False, False],
                                #  [True, True, True, False, False],
                                #  [True, True, False, False, False]]
```

For transformer training and inference, one has to deal with `input_ids`, `label` and `attention_mask`. The idea of this function, combinese with `pad_to` are useful. 

I'm not shameless enough to share how primitive I was doing before getting used to thinking in tensors. 

In [54]:
def seq_mask(len_B: list[int], maxlen: int):
    """assume maxlen >= len of longest seq in the len_B
    B: batch size
    maxlen: pad the batch to this len
    """
    return len_B[:, None] > arange(maxlen)

In [55]:
seq_mask(tensor([1, 3, 2]), 5)

array([[ True, False, False, False, False],
       [ True,  True,  True, False, False],
       [ True,  True, False, False, False]])

In [56]:
# test
result_1 = seq_mask(tensor([1, 3, 2]), 5)
expected_1 = np.array([[True, False, False, False, False],
                        [True, True, True, False, False],
                        [True, True, False, False, False]])
assert np.array_equal(result_1, expected_1), f"Test 1 failed: expected {expected_1}, got {result_1}"

result_2 = seq_mask(tensor([0, 4, 1]), 4)
expected_2 = np.array([[False, False, False, False],
                        [True, True, True, True],
                        [True, False, False, False]])
assert np.array_equal(result_2, expected_2), f"Test 2 failed: expected {expected_2}, got {result_2}"

result_3 = seq_mask(tensor([5]), 5)
expected_3 = np.array([[True, True, True, True, True]])
assert np.array_equal(result_3, expected_3), f"Test 3 failed: expected {expected_3}, got {result_3}"

## [bincount](https://numpy.org/doc/stable/reference/generated/numpy.bincount.html)

In [57]:
# example
np.bincount(np.array([0, 1, 1, 3, 2, 1, 7]))

array([1, 3, 1, 1, 0, 0, 0, 1])

In [58]:
def bincount(a_i):
    max = a_i.max()
    i = a_i.shape[0]

    counting = arange(max + 1)[:, None] == a_i  # (max, i)
    reduce = where(counting, 1, 0) @ ones(i)

    return reduce

In [59]:
bincount(tensor([0, 1, 1, 3, 2, 1, 7]))

array([1, 3, 1, 1, 0, 0, 0, 1])

In [60]:
# test
my_result_1 = bincount(tensor([0, 1, 1, 3, 2, 1, 7]))
np_result_1 = np.bincount(np.array([0, 1, 1, 3, 2, 1, 7]))
assert np.array_equal(my_result_1, np_result_1), f"Test 1 failed: expected {np_result_1}, got {my_result_1}"

my_result_2 = bincount(tensor([2, 3, 3, 2, 4]))
np_result_2 = np.bincount(np.array([2, 3, 3, 2, 4]))
assert np.array_equal(my_result_2, np_result_2), f"Test 2 failed: expected {np_result_2}, got {my_result_2}"

my_result_3 = bincount(tensor([0, 0, 0]))
np_result_3 = np.bincount(np.array([0, 0, 0]))
assert np.array_equal(my_result_3, np_result_3), f"Test 3 failed: expected {np_result_3}, got {my_result_3}"


## [scatter add](https://pytorch-scatter.readthedocs.io/en/1.3.0/functions/add.html)
![](https://raw.githubusercontent.com/rusty1s/pytorch_scatter/master/docs/source/_figures/add.svg?sanitize=true)

The idea is related to `bincount` and `sequence mask`. Expand and reduce with matmul.

In [61]:
def scatter_add(a_i, index_i):
    n = index_i.max() + 1  # number of attributions

    expand = arange(n)[:, None] == index_i  # (n, i)
    reduce = where(expand, 1, 0) @ a_i  # (n, i) @ (i,) = (n,)

    return reduce
    

In [62]:
a = tensor([5, 1, 7, 2, 3, 2, 1, 3])
index = tensor([0, 0, 1, 0, 2, 2, 3, 3])

scatter_add(a, index)

array([8, 7, 5, 4])

In [63]:
# test
result_1 = scatter_add(tensor([5, 1, 7, 2, 3, 2, 1, 3]), tensor([0, 0, 1, 0, 2, 2, 3, 3]))
expected_1 = np.array([8, 7, 5, 4])
assert np.array_equal(result_1, expected_1), f"Test 1 failed: expected {expected_1}, got {result_1}"

result_2 = scatter_add(tensor([2, 4, 1, 3]), tensor([1, 1, 0, 1]))
expected_2 = np.array([1, 9])
assert np.array_equal(result_2, expected_2), f"Test 2 failed: expected {expected_2}, got {result_2}"

result_3 = scatter_add(tensor([0, 0, 0, 0]), tensor([0, 1, 2, 3]))
expected_3 = np.array([0, 0, 0, 0])
assert np.array_equal(result_3, expected_3), f"Test 3 failed: expected {expected_3}, got {result_3}"

## [flattern](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flatten.html)

In [64]:
# example
a = arange(12).reshape((3, 4))
a, a.flatten()

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]))

In [65]:
arange(12) // 4

array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2])

In [66]:
def flatten(a_ij):
    i, j = a_ij.shape
    return a_ij[arange(i * j) // j, arange(i * j) % j]

In [67]:
flatten(a)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [68]:
# test
a_test_1 = np.array([[1, 2], [3, 4]])
expected_1 = a_test_1.flatten()
result_1 = flatten(a_test_1)
assert np.array_equal(result_1, expected_1), f"Test 1 failed: expected {expected_1}, got {result_1}"

a_test_2 = np.array([[0, 0, 0], [0, 0, 0]])
expected_2 = a_test_2.flatten()
result_2 = flatten(a_test_2)
assert np.array_equal(result_2, expected_2), f"Test 2 failed: expected {expected_2}, got {result_2}"

a_test_3 = np.array([[9]])
expected_3 = a_test_3.flatten()
result_3 = flatten(a_test_3)
assert np.array_equal(result_3, expected_3), f"Test 3 failed: expected {expected_3}, got {result_3}"

## [linspace](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html)

In [69]:
# example
np.linspace(2, 3, 5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [70]:
def linspace(start, stop, n: int):
    """inclusive for both start and stop"""
    step = (stop - start) / (n - 1)
    return start + step * arange(n)

In [71]:
linspace(2, 3, 5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [72]:
# test
test_1_start, test_1_stop, test_1_n = -10, 0, 5
expected_1 = np.linspace(test_1_start, test_1_stop, test_1_n)
result_1 = linspace(test_1_start, test_1_stop, test_1_n)
assert np.allclose(result_1, expected_1), f"Test 1 failed: expected {expected_1}, got {result_1}"

test_2_start, test_2_stop, test_2_n = 0, 100, 20
expected_2 = np.linspace(test_2_start, test_2_stop, test_2_n)
result_2 = linspace(test_2_start, test_2_stop, test_2_n)
assert np.allclose(result_2, expected_2), f"Test 2 failed: expected {expected_2}, got {result_2}"

test_3_start, test_3_stop, test_3_n = -50, 50, 2
expected_3 = np.linspace(test_3_start, test_3_stop, test_3_n)
result_3 = linspace(test_3_start, test_3_stop, test_3_n)
assert np.allclose(result_3, expected_3), f"Test 3 failed: expected {expected_3}, got {result_3}"

## [heaviside](https://numpy.org/doc/stable/reference/generated/numpy.heaviside.html)
```python
                      0   if x1 < 0
heaviside(x1, x2) =  x2   if x1 == 0
                      1   if x1 > 0
```

In [73]:
np.heaviside([-1.5, 0, 2.0], 1)

array([0., 1., 1.])

In [74]:
def heaviside(a_i, b):
    return where(a_i == 0, b, where(a_i > 0, 1, 0))

In [75]:
heaviside(tensor([-1.5, 0, 2.0]), 1)

array([0, 1, 1])

In [76]:
# test
test_1_input = np.array([-2.5, 0, 3.5])
expected_1 = np.heaviside(test_1_input, 0.5)
result_1 = heaviside(test_1_input, 0.5)
assert np.allclose(result_1, expected_1), f"Test 1 failed: expected {expected_1}, got {result_1}"

test_2_input = np.array([-100, -50, 0, 50, 100])
expected_2 = np.heaviside(test_2_input, 0.8)
result_2 = heaviside(test_2_input, 0.8)
assert np.allclose(result_2, expected_2), f"Test 2 failed: expected {expected_2}, got {result_2}"

test_3_input = np.array([0])
expected_3 = np.heaviside(test_3_input, 0)
result_3 = heaviside(test_3_input, 0)
assert np.allclose(result_3, expected_3), f"Test 3 failed: expected {expected_3}, got {result_3}"

## [repeat(1d)](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

The effect of `np.tile`, but only expand on `dim=0`. 


In [77]:
# example
np.tile(arange(3), (5, 1))

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [78]:
def repeat(a_i, n: int):
    return ones(n)[:, None] * a_i

In [79]:
repeat(arange(3), 5)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [80]:
# test
test_1_input = arange(4)
n_1 = 3
expected_1 = np.tile(test_1_input, (n_1, 1))
result_1 = repeat(test_1_input, n_1)
assert np.array_equal(result_1, expected_1), f"Test 1 failed: expected {expected_1}, got {result_1}"

test_2_input = tensor([5])
n_2 = 10
expected_2 = np.tile(test_2_input, (n_2, 1))
result_2 = repeat(test_2_input, n_2)
assert np.array_equal(result_2, expected_2), f"Test 2 failed: expected {expected_2}, got {result_2}"

test_3_input = linspace(0, 1, 5)
n_3 = 2
expected_3 = np.tile(test_3_input, (n_3, 1))
result_3 = repeat(test_3_input, n_3)
assert np.array_equal(result_3, expected_3), f"Test 3 failed: expected {expected_3}, got {result_3}"


# [bucketize](https://pytorch.org/docs/stable/generated/torch.bucketize.html)

Returns the **indices** of the buckets to which each value in the input belongs.

```python
a = torch.tensor([3, 6, 9])
boundary = torch.tensor([1, 3, 5, 7, 9])

torch.bucketize(a, boundary) -> tensor([1, 3, 4])
```

In [81]:
def bucketize(a_i, boundary_j):
    """boundary has to be in monotonically increasing order."""
    j = boundary_j.shape[0]
    return where(a_i[:, None] > boundary_j, 1, 0) @ ones(j)

In [82]:
a = tensor([3, 6, 9])
boundary = tensor([1, 3, 5, 7, 9])

bucketize(a, boundary)

array([1, 3, 4])

In [83]:
# test
test_1_input = tensor([0, 5, 10])
boundary_1 = tensor([0, 3, 6, 9])
expected_1 = tensor([0, 2, 4])
result_1 = bucketize(test_1_input, boundary_1)
assert np.array_equal(result_1, expected_1), f"Test 1 failed: expected {expected_1}, got {result_1}"

test_2_input = tensor([-5, 0, 5, 10])
boundary_2 = tensor([-10, -5, 0, 5, 10])
expected_2 = tensor([1, 2, 3, 4])
result_2 = bucketize(test_2_input, boundary_2)
assert np.array_equal(result_2, expected_2), f"Test 2 failed: expected {expected_2}, got {result_2}"

test_3_input = tensor([1, 2, 3, 4, 5])
boundary_3 = tensor([1, 3, 5])
expected_3 = tensor([0, 1, 1, 2, 2])
result_3 = bucketize(test_3_input, boundary_3)
assert np.array_equal(result_3, expected_3), f"Test 3 failed: expected {expected_3}, got {result_3}"
